const cardData = [
    // ==========================================
    // ★5 概念・最高位（5種）
    // ==========================================
    { id: 3001, name: "原初の火 軻遇突智", rare: 5, attr: "fire", story: "全てが始まる前に存在したとされる、純粋な熱量そのもの。観測者の世界を燃やし尽くす。", bonus: 50.0 },
    { id: 3002, name: "創世の海 ティアマト", rare: 5, attr: "water", story: "生命の源たる原初の海。彼女が波打つ時、世界は再び無垢なる霊貨の海へと沈む。", bonus: 5.0 },
    { id: 3003, name: "創世の母神 ガイア", rare: 5, attr: "earth", story: "大地という概念を生み出した母なる存在。彼女の気まぐれは世界を容易く裏返してしまう。", bonus: 0.1 },
    { id: 3004, name: "天理の神 アマツ", rare: 5, attr: "sky", story: "天上の理を統べる最高位の神。その眼差しは運命を書き換え、稀なる神結晶をこの世に顕現させる。", bonus: 0.005 },
    { id: 3005, name: "忘却の神 レテ", rare: 5, attr: "evil", story: "深淵に座し、全てを無へと還す神。その沈黙は既存の理を塗り替え、あらゆる現象を底知れぬ力へと変貌させる。", bonus: 0.5 },

    // ==========================================
    // ★4 神・大罪の魔将（10種）
    // ==========================================
    { id: 2001, name: "業火の神 カグツチ", rare: 4, attr: "fire", story: "神代より続く、万物を焼き清める原始の炎。その焔は観測者の魂を燃え上がらせる。", bonus: 10.0 },
    { id: 2002, name: "憤怒の魔将 サタン", rare: 4, attr: "fire", story: "【大罪：憤怒】血塗られた剣を振るう地獄の将。彼の怒りに触れた者は限界を超えた力を引き出される。", bonus: 15.0 },
    { id: 2003, name: "深海の王 ワダツミ", rare: 4, attr: "water", story: "海の底で永い眠りについていた古き神。その息吹は潮の満ち引きと共に富の奔流を生む。", bonus: 0.5 },
    { id: 2004, name: "嫉妬の海神 レヴィアタン", rare: 4, attr: "water", story: "【大罪：嫉妬】他者の富を貪り喰らう深淵の海獣。その果てなき渇望が霊貨の波を呼び寄せる。", bonus: 0.8 },
    { id: 2005, name: "岩穿の巨神", rare: 4, attr: "earth", story: "拳一つで山を砕く伝説の巨人。彼が大地を叩く衝撃は、観測の一撃をより致命的なものへと変える。", bonus: 0.03 },
    { id: 2006, name: "強欲の地主 マモン", rare: 4, attr: "earth", story: "【大罪：強欲】地中の黄金を全て我が物とする魔神。彼の欲望はわずかな確率の奇跡を強引に引き当てる。", bonus: 0.05 },
    { id: 2007, name: "雷霆の竜神", rare: 4, attr: "sky", story: "天を裂く雷の化身。その一閃は次元の壁を穿ち、神の領域から結晶をこぼれ落とさせる。", bonus: 0.001 },
    { id: 2008, name: "傲慢の堕天使 ルシファー", rare: 4, attr: "sky", story: "【大罪：傲慢】かつて天の頂にいた最も美しき者。神をもしのぐその傲慢さは、希少な結晶すら傅かせる。", bonus: 0.002 },
    { id: 2009, name: "暴食の王 ベルゼブブ", rare: 4, attr: "evil", story: "【大罪：暴食】あらゆるものを喰らい尽くす蝿の王。彼が存在するだけで、獲得の概念そのものが膨張し続ける。", bonus: 0.1 },
    { id: 2010, name: "色欲の魔神 アスモデウス", rare: 4, attr: "evil", story: "【大罪：色欲】欲望の果てに座す魔神。魅了された者は、自身の魂すらも霊貨に変えて捧げてしまう。", bonus: 0.12 },

    // ==========================================
    // ★3 上級精霊・亜神（10種）
    // ==========================================
    { id: 1001, name: "鳳凰の雛 焔", rare: 3, attr: "fire", story: "神鳥の幼生。まだ飛べぬものの、その羽ばたきは太陽の欠片のように周囲を照らし出す。", bonus: 2.0 },
    { id: 1002, name: "炎蛇の化身", rare: 3, attr: "fire", story: "マグマ溜まりから生まれ落ちた蛇神。這った跡には消えない炎が残る。", bonus: 3.0 },
    { id: 1003, name: "清流の使者 アオ", rare: 3, attr: "water", story: "清らかな川の流れを司る龍の末裔。彼女の加護を受けた地では、あらゆる交易が盛んになる。", bonus: 0.1 },
    { id: 1004, name: "氷雪の精霊王", rare: 3, attr: "water", story: "絶対零度を支配する王。霊貨の価値を凍結し、より高い倍率のまま保存する。", bonus: 0.15 },
    { id: 1005, name: "豊穣の女神", rare: 3, attr: "earth", story: "実りの秋を司る神。彼女の歩みと共に黄金の麦が芽吹き、会心の奇跡を呼ぶ。", bonus: 0.01 },
    { id: 1006, name: "怠惰の魔獣 ベルフェゴール", rare: 3, attr: "earth", story: "【大罪：怠惰】動くことを拒んだ結果、大地と一体化した巨獣。彼の重みは一撃の威力を致命的な域に達しさせる。", bonus: 0.02 },
    { id: 1007, name: "嵐の精霊 ジン", rare: 3, attr: "sky", story: "竜巻の中心に住まう風の精霊。全てを巻き上げる風は、隠された宝をも空へ打ち上げる。", bonus: 0.0002 },
    { id: 1008, name: "黄金の霊鳥", rare: 3, attr: "sky", story: "夕暮れの空を飛ぶ神々しい鳥。その羽が落ちた場所には必ず神の欠片が埋まっているという。", bonus: 0.0003 },
    { id: 1009, name: "誘惑の悪魔 リリス", rare: 3, attr: "evil", story: "夜の帳から現れる美しき魔性。彼女との契約は甘美な報酬を約束するが、それは世界の秩序を歪める禁忌の力。", bonus: 0.05 },
    { id: 1010, name: "怨嗟の亡霊騎士", rare: 3, attr: "evil", story: "生前の恨みを力に変えて戦い続ける騎士。その怨念は乗算となって世界を侵食する。", bonus: 0.06 },

    // ==========================================
    // ★2 中級精霊・妖（50種）
    // ==========================================
    { id: 100, name: "荒ぶる鬼火", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 101, name: "輝く狐火", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 102, name: "目覚めし火精", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 103, name: "怒れる灯火", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 104, name: "嘆きの焔", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 105, name: "紅蓮の使い魔", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 106, name: "業火の妖精", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 107, name: "灼熱の番犬", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 108, name: "天駆ける火の鳥", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 109, name: "深き森の火蜥蜴", rare: 2, attr: "fire", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.5 },
    { id: 110, name: "荒ぶる河童", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 111, name: "輝く泉の妖精", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 112, name: "目覚めし水精", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 113, name: "怒れる波浪", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 114, name: "嘆きの雨女", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 115, name: "蒼流の使い魔", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 116, name: "深海の妖魔", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 117, name: "激流の番人", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 118, name: "天駆ける水龍", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 119, name: "氷の城の騎士", rare: 2, attr: "water", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.03 },
    { id: 120, name: "荒ぶる土偶", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 121, name: "輝く鉱石の霊", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 122, name: "目覚めしゴーレム", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 123, name: "怒れる岩石", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 124, name: "嘆きの砂男", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 125, name: "大地の使い魔", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 126, name: "豊穣の妖精", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 127, name: "岩窟の番犬", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 128, name: "地を駆ける獣", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 129, name: "鋼の城の騎士", rare: 2, attr: "earth", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.003 },
    { id: 130, name: "荒ぶる雷獣", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 131, name: "輝く天馬", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 132, name: "目覚めし風精", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 133, name: "怒れる積乱雲", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 134, name: "嘆きの鳥人", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 135, name: "天空の使い魔", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 136, name: "雷光の妖魔", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 137, name: "高みの番人", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 138, name: "天を裂く鷹", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 139, name: "雲海の騎士", rare: 2, attr: "sky", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.00005 },
    { id: 140, name: "荒ぶる夢魔", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 141, name: "輝く呪具", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 142, name: "目覚めし亡霊", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 143, name: "怒れる死霊", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 144, name: "嘆きの怨霊", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 145, name: "深淵の使い魔", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 146, name: "漆黒の妖魔", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 147, name: "黄泉の番犬", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 148, name: "夜を駆ける影", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },
    { id: 149, name: "冥府の騎士", rare: 2, attr: "evil", story: "少し名を知られ始めた霊的存在。明確に観測の助けとなる。", bonus: 0.01 },

    // ==========================================
    // ★1 下級精霊・付喪神（100種）
    // ==========================================
    { id: 0, name: "迷える灯火", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 1, name: "名もなき火種", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 2, name: "小さな火の粉", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 3, name: "路地裏の燐光", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 4, name: "古びた火打石", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 5, name: "忘れられた蝋燭", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 6, name: "微かな温もり", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 7, name: "夢見る火精", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 8, name: "眠たげな竃", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 9, name: "踊る狐火", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 10, name: "静かな残り火", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 11, name: "透明な熱気", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 12, name: "囁く火精", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 13, name: "隠れた熾火", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 14, name: "遠い焚き火", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 15, name: "紅き妖精", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 16, name: "朱色の粒子", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 17, name: "燃える欠片", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 18, name: "熱を帯びた影", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 19, name: "陽だまりの精", rare: 1, attr: "fire", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.1 },
    { id: 20, name: "迷える水滴", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 21, name: "名もなき雫", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 22, name: "小さな朝露", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 23, name: "路地裏の puddle", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 24, name: "古びた水鏡", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 25, name: "忘れられた井戸", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 26, name: "微かな波紋", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 27, name: "夢見る水精", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 28, name: "眠たげな小川", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 29, name: "踊る飛沫", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 30, name: "静かな水たまり", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 31, name: "透明な雨粒", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 32, name: "囁く泉", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 33, name: "隠れた湧水", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 34, name: "遠いせせらぎ", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 35, name: "蒼き妖精", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 36, name: "水色の粒子", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 37, name: "濡れた欠片", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 38, name: "湿気を帯びた影", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 39, name: "霧の精", rare: 1, attr: "water", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.01 },
    { id: 40, name: "迷える小石", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 41, name: "名もなき土塊", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 42, name: "小さな砂粒", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 43, name: "路地裏の泥", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 44, name: "古びた茶碗", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 45, name: "忘れられた道祖神", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 46, name: "微かな振動", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 47, name: "夢見る土精", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 48, name: "眠たげな岩", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 49, name: "踊る砂塵", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 50, name: "静かな土手", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 51, name: "無骨な石ころ", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 52, name: "囁く大地", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 53, name: "隠れた鉱脈", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 54, name: "遠い山鳴り", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 55, name: "茶色の妖精", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 56, name: "土の粒子", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 57, name: "硬い欠片", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 58, name: "土を帯びた影", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 59, name: "地割れの精", rare: 1, attr: "earth", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.001 },
    { id: 60, name: "迷える風", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 61, name: "名もなき羽", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 62, name: "小さな雲", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 63, name: "路地裏の隙間風", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 64, name: "古びた風鈴", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 65, name: "忘れられた凧", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 66, name: "微かな気流", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 67, name: "夢見る風精", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 68, name: "眠たげなそよ風", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 69, name: "踊る落ち葉", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 70, name: "静かな空", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 71, name: "透明な息吹", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 72, name: "囁くつむじ風", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 73, name: "隠れた上昇気流", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 74, name: "遠い雷鳴", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 75, name: "白き妖精", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 76, name: "空色の粒子", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 77, name: "軽い欠片", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 78, name: "風を帯びた影", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 79, name: "高天の精", rare: 1, attr: "sky", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.00001 },
    { id: 80, name: "迷える影", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 81, name: "名もなき怨念", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 82, name: "小さな悪意", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 83, name: "路地裏の澱み", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 84, name: "古びた呪具", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 85, name: "忘れられた儀式", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 86, name: "微かな殺気", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 87, name: "夢見る悪魔", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 88, name: "眠たげな使い魔", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 89, name: "踊る亡霊", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 90, name: "静かな呪い", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 91, name: "透明な毒", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 92, name: "囁く狂気", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 93, name: "隠れた嫉妬", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 94, name: "遠い悲鳴", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 95, name: "紫の妖精", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 96, name: "闇色の粒子", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 97, name: "淀んだ欠片", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 98, name: "死を帯びた影", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 },
    { id: 99, name: "深淵の精", rare: 1, attr: "evil", story: "八百万の末端に位置する小さな存在。観測の助けとなる。", bonus: 0.005 }
];
